server:
  port: ${services.rosco.port:8087}
  address: ${services.rosco.host:localhost}

redis:
  connection: ${services.redis.connection:redis://localhost:6379}

aws:
  enabled: ${providers.aws.enabled:false}
  bakeryDefaults:
    awsAccessKey: ${providers.aws.primaryCredentials.access_key_id}
    awsSecretKey: ${providers.aws.primaryCredentials.secret_key}

docker:
  enabled: ${services.docker.enabled:false}
  bakeryDefaults:
    targetRepository: ${services.docker.targetRepository}

google:
  enabled: ${providers.google.enabled:false}
  accounts:
    - name: ${providers.google.primaryCredentials.name}
      project: ${providers.google.primaryCredentials.project}
      jsonPath: ${providers.google.primaryCredentials.jsonPath}
  gce:
    bakeryDefaults:
      zone: ${providers.google.defaultZone}

rush:
  baseUrl: ${services.rush.baseUrl:localhost:8085}
  configDir: ${services.rush.configDir}
